using System.ComponentModel.DataAnnotations;

namespace BookstoreApp.Models
{
    // Represents a single Book record in the system
    public class Book
    {
        // Primary key (auto generated by EF Core)
        public int Id { get; set; }

        // Book title - mandatory
        [Required(ErrorMessage = "Title is required")]
        [StringLength(200, ErrorMessage = "Title cannot be longer than 200 characters")]
        public string Title { get; set; } = string.Empty;

        // Book author - mandatory
        [Required(ErrorMessage = "Author is required")]
        [StringLength(150, ErrorMessage = "Author name cannot be longer than 150 characters")]
        public string Author { get; set; } = string.Empty;

        // Genre is optional
        [StringLength(100, ErrorMessage = "Genre cannot be longer than 100 characters")]
        public string? Genre { get; set; }

        // Book price - mandatory and must be positive
        [Required(ErrorMessage = "Price is required")]
        [Range(0.01, 100000, ErrorMessage = "Price must be between 0.01 and 100000")]
        public decimal Price { get; set; }
    }
}
